### ISSUE TITLE
Overall maintaining status

### ISSUE THREAD

**Issue by knalli** [wuyuntao/jquery-autosuggest#25]
Hi, 

I'd sent you a mail a few days ago using the profile's mail address. Seems not to be reliable.

I'm interested in your further plans about this project. Do you want to maintain it, or is that out of scope?

We had chosen that plugin (formely the 1.4er of Drew Wilson) for our application. Still in developing, we had noticed few weeks ago that the plugin is extremly unsafe in context of some issues with XSS (cross site scripting). Even on Drew Wilson website I can inject JavaScript easily. 

Actually, this is already fixed in our own topic branch at https://github.com/hlsolutions/jquery-autosuggest/tree/advanced-rendering-and-xss-protection, but I'm waiting for the other PR.

If you are out of time or have don't like it to maintain further, I won't provide the pull requests. In that case, I would ask the outstanding PRs to re-integrate a patch for me..

best regards,
Jan

**Comment by wuyuntao** [comment]
Sorry for late response. This project is still alive and feel free to open a pull request.

**Comment by knalli** [comment]
Hm, okay. However, actually, there are still a couple of open requests without any further reactions. Don't get me wrong, but I'm just surveying how to handle the changes.

**Comment by knalli** [comment]
So, three months went away.

In the meantime, I released yesterday the next release of AutoSuggest 2 at https://github.com/hlsolutions/jquery-autosuggest/. The big change is the transition to [CoffeeScript](https://github.com/jashkenas/coffee-script) and SASS in combination to [Grunt](https://github.com/cowboy/grunt) and post commit tests with Travis. Please note the changelog because some events had been renamed.

Everyone is invited to send us PRs if you want.
