### ISSUE TITLE
Prevent users from adding anything that is not in the results list

### ISSUE THREAD

**Issue by jerefrer** [wuyuntao/jquery-autosuggest#33]
I'm in a situation where I need to prevent the users from creating anything and just allow them to select items shown in the result list.

I don't think there is an easy way to do this, so [I asked the question on SO and added my way of doing it](http://stackoverflow.com/questions/18054194/how-to-force-autosuggest-to-restrict-addition-to-search-result/18054246#18054246).

But I think this if far from ideal, what's your take on this ? Maybe there should be an option to do just that ?

**Comment by jerefrer** [comment]
Turns out there is a better and maintained version of this plugin that already has this feature. Check this out : https://github.com/hlsolutions/jquery-autosuggest

PS : I had no issue at all when migrating from the old plugin to the new one. It was as simple as replacing the JS file.

**Comment by knalli** [comment]
Just for the record: I've marked breaking changes in the changelog.
