### ISSUE TITLE
Ignores the initial contents of input's value attribute

### ISSUE THREAD

**Issue by necolas** [wuyuntao/jquery-autosuggest#8]
For example, say you use this plugin in a web app that allows you to tag item (like delicious). Your web app also has an option to "edit tags" but if you include all the existing tags in the input's value attribute:

input value="dog, ball, sun, beach"

...the plugin appears to ignore this entirely. It would be great if it could populate the existing tags from the value retrieved from the server. This would make edits to selected tags possible.

**Comment by wuyuntao** [comment]
We already have a way to intial the autosuggest box by setting the preFill option.
